### ISSUE TITLE
Return failure for exile/ban reason being over 512 characters

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#126]
A case occurred where we tried to ban a user and the reason was too long which failed the ban process. To improve UX, the failed command should return why the command failed. ![image](https://github.com/user-attachments/assets/548ca597-c490-4fa4-bb0b-67f7a8ea46e9)

**Comment by brtran4** [comment]
we can probably just parse the json the just use the `message` and throw it to the mod logging channel, but we should probably make sure that the error messages are in the same exact format

example error message:
```
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"reason": {"_errors": [{"code": "BASE_TYPE_MAX_LENGTH", "message": "Must be 512 or fewer in length."}]}}}
```

**Comment by clairefleuret** [comment]
Assigned @Alex-Gideon
