### ISSUE TITLE
Re-organize code in Exile command

### ISSUE THREAD

**Issue by OTCompa** [naurffxiv/moddingway#19]
Currently, there are 2 `if hasDuration` blocks broken up code to exile the user, which there is probably a better way around.
We could just combine both if blocks and move exiling the user to within the blocks to make the code more readable at the expense of some duplicated code.

**Comment by clairefleuret** [comment]
Adding task to re-organize how logging works.

Instead of being dynamically set, we can have it be static.

Channel ID: 1172324840947056681

**Comment by brtran4** [comment]
> Adding task to re-organize how logging works.
> 
> Instead of being dynamically set, we can have it be static.
> 
> Channel ID: 1172324840947056681

@clairefleuret we should split this to be its own issue for logging. this is specifically for the exile/unexile code
