### ISSUE TITLE
When setting a mod log channel, change the confirmation to a message the channel set

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#24]
Would be a better implementation if we have a confirmation message in the channel rather than an echo.

**Comment by brtran4** [comment]
i actually don't know what this looks like. can you quick send a screenshot?

**Comment by clairefleuret** [comment]
![image](https://github.com/naurffxiv/moddingway/assets/170650581/597341b9-f06f-49c6-8a33-543516a2e7a8)
Perhaps we just leave the message but the message is sent to the channel that was set

**Comment by clairefleuret** [comment]
@brtran4
