### ISSUE TITLE
Basic Moderation - Ban Command

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#37]
Ban - Ability to ban/unban. Notify user reason via dms
	/ban <user> <reason>
	/unban <user> <reason>

**Comment by clairefleuret** [comment]
@brtran4 is this done, showing inprogress in the board

**Comment by brtran4** [comment]
Yeah it's still missing unban

**Comment by brtran4** [comment]
Gonna split this into #77 and closing this issue
