### ISSUE TITLE
Basic Moderation - Slowmode command

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#39]
Slowmode - Add/remove slowmode with durations
	/slowmode <duration in secs/minutes/hours>
	/slowmodeoff

**Comment by brtran4** [comment]
should there be specified channels? or is this to every single channel? @clairefleuret

**Comment by clairefleuret** [comment]
> should there be specified channels? or is this to every single channel? @clairefleuret

all channels is fine if its easier

**Comment by brtran4** [comment]
> > should there be specified channels? or is this to every single channel? @clairefleuret
> 
> all channels is fine if its easier

i think it would be easier if it was only one channel tbh

**Comment by clairefleuret** [comment]
@brtran4 we can actually scrap this, i have a different idea that we can use with carlbot
