### ISSUE TITLE
Strike System - Commands

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#46]
Strike System TL;DR

1 strike - warning
2 strikes - 24 hour exile 
3 strikes - 48 hour exile 
> 3 strikes - Indefinite exile

Prior to 2 strikes: DM user that they have been striked. Continuing to obtain strikes will lead to Exile, a timeout with no access to social channels.
2 Strikes: DM user they have been auto-exiled for 24 hours for obtaining a total of 3 strikes. After their exile, if they continue to get striked, punishments will become more severe.
3 Strikes: DM user they have been auto-exiled for 48 hours for obtaining a total of 4 strikes. If they continue to earn strikes, their next punishment will lead to an indefinite exile from the server.
> 3 Strikes: DM user they have been indefinitely exiled for obtaining more than 3 strikes. They may appeal this ban at a later date.

Commands

Add strike - Should notify the user of the warning and reason
	/strike <user> <reason>
Clear strikes- Remove ALL strikes
	/clearstrikes <user>
Delete specific strikes - Removes a specific warning
	/deletestrike <warningID>
Show all current strikes- Shows all warnings for a user.
	/strikes <user>
Show all current strikes - Add a command to DM the bot to list all active strikes for the person that DM’d the bot
		!stikes

**Comment by brtran4** [comment]
we're treating this as an epic, so feel free to cut down the work into smaller issues @OTCompa

**Comment by clairefleuret** [comment]
Closing to re-evaluate scope since moderation changes are happenieng.
