### ISSUE TITLE
Note System - Commands

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#47]
Commands

Add note - Add a note to a user that only mods can see
	/addnote <user> <reason for note>
Show specific note - Shows a specific note
	/shownote <note ID>
Show all notes - Shows all notes for a user
	/shownotes <user>
Delete specific note - Deletes a specific note
	/deletenote <noteID>
Delete all notes - Deletes all notes from a user
	/clearnotes <user>

**Comment by brtran4** [comment]
we're treating this as an epic, so feel free to spread this work into smaller issues @KingPieson

**Comment by clairefleuret** [comment]
Closing to re-evaluate scope since moderation changes are happening.
