### ISSUE TITLE
Remove unneeded commands

### ISSUE THREAD

**Issue by brtran4** [naurffxiv/moddingway#84]
we should remove the following commands and code stubs

- `/slowmode`
- `/slowmodeoff`
- `/kick`

**Comment by MachoMaheen** [comment]
Can you check my PR. I commented out the related code stubs. Do i need to remove or is commenting out is enough?

**Comment by brtran4** [comment]
> Can you check my PR @brtran4 . I commented out the related code stubs. Do i need to remove or is commenting out is enough?

let's remove the code out entirely

**Comment by MachoMaheen** [comment]
Removed all the unneeded commands and also from the AddCommands function @brtran4
