### ISSUE TITLE
Exile - Exile Statuses Command

### ISSUE THREAD

**Issue by clairefleuret** [naurffxiv/moddingway#85]
We need a command that pulls the current active exiles and prints them out in a message.

If possible would want the following info:
- Person exiled
- Time remaining
- Moderator who issued the exile

**Comment by clairefleuret** [comment]
Being addressed in https://github.com/naurffxiv/moddingway/pull/128

**Comment by brtran4** [comment]
from #132 

We want Moddingway to be able to look at previous entries of exiles. This only needs to be person. The command should be called "exilereport" and the only argument would be the user. The returned values should be all records for the user. This can all be done in an ephemeral message. Example below:

Command: /exilereport

```
<Exile ID> <Date> <Reason> <Moderator>
<Exile ID> <Date> <Reason> <Moderator>
<Exile ID> <Date> <Reason> <Moderator>
```
